### ISSUE TITLE
Wrap long (SPF) records e.g. containing DKIM values

### ISSUE THREAD

**Issue by osos** [shupp/VegaDNS#19]
If the records are long, they force the table to expand due to nowrap. Please allow/force word-wrapping on the records "Address" column.

eg.
[code]
 `<table .... style="table-layout:fixed">`
...
`<td style="word-wrap:break-word"> long SPF record with DKIM data </td>`
[/code]

**Comment by shupp** [comment]
This will be in 0.13.0.  Thanks!
