### ISSUE TITLE
CNAME records cannot contaion underscrore (_)

### ISSUE THREAD

**Issue by osos** [shupp/VegaDNS#22]
in the fight against e-mail spam, the DKIM system has been in place for a long time.

For this I had a sub._domainkey.domain.tld TXT record with the DKIM key.

However, now my new SMTP provider has the option to implement his key via CNAME such as:

sub1._domainkey.domain.tld CNAME dkim1.smtpprovider.tld
sub2._domainkey.domain.tld CNAME dkim2.smtpprovider.tld

Vegadns tells me this is not a valid CNAME record name.

I guess the validation of CNAME records should allow for underscores.

**Comment by osos** [comment]
Probably it is in this line, but havent testet:
https://github.com/shupp/VegaDNS/blob/e8314768dd50e28d011b21fea7f7cc30e7202c42/src/functions.php#L167

**Comment by shupp** [comment]
This should already be fixed in the 0.13.0-test branch, which will be released shortly.  The change is here:

https://github.com/shupp/VegaDNS/commit/2da488cb6c4aa5a32182c8f1fd6bb1273c6ca64b

Can you try the 0.13.0-test branch and confirm?  (No expected changes before release at this time)

**Comment by shupp** [comment]
0.13.0 is now out, and contains the fix listed above.
