### ISSUE TITLE
Edit default record error

### ISSUE THREAD

**Issue by blackyzero** [shupp/VegaDNS#24]
Hello,
i am using version 0.13.0 on Freebsd 10.2, end getting this error message when trying to edit the default record.
Array ( [0] => HY000 [1] => 1366 [2] => Incorrect integer value: '' for column 'record_id' at row 1 ) 1

In addition, there is no domain appears on VegaDNS after created, although they appears on mysql database.

Also tested with 0.12.1 version.

Please anyone help me on this.
Thank you.

**Comment by shupp** [comment]
Thanks for the report.  I'll investigate this shortly and get back.  You might try 0.13.1 in the meantime, which fixes at least one known issue.

**Comment by blackyzero** [comment]
Hi Shupp,

Thanks for swift respond.
I installed latest version 0.13.1 and still getting this error. You can see the screenshot here,
http://imgur.com/MP0bl8k

I am running mysql5.6.26

Thanks again.

**Comment by shupp** [comment]
I've fixed a couple of queries in b023e2281fcfb227d15e078fc2db55ea9dd4cc4a.  Can you check out master and try again?  It sounds like this is a fresh install.. if so, would you mind dropping the tables so the original data is seeded properly?  Let me know if it solves your issues and I can get this rolled out in a release.

**Comment by blackyzero** [comment]
Hi Shupp,

Thanks for your respond.
I reinstall everything with current Master file, and get different error as below:
Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', '86400', 'group')' at line 7 ) 1

I also attach the screenshot of existing admin account.
Could you please check this?

Thank you.

<img width="459" alt="screen shot 2015-10-28 at 10 48 57 am" src="https://cloud.githubusercontent.com/assets/4286063/10779305/86c59d28-7d61-11e5-9fcf-64f228c88b5c.png">

**Comment by shupp** [comment]
Thanks for reporting.. it looks as though you got this when trying to edit the SOA when logged in as a group_admin.  I've fixed this SQL statement and pushed to master.. can you check out master again and retry?

**Comment by blackyzero** [comment]
Great. Thanks Shupp, the sql statement is gone, but i found another issue.
After edit default record, it shows correctly, however when i click on Default Record -> edit, it doesn't update the current Primary Name Server, only show default "ns1.myserver.com" (attachment the image)
![screen shot 2015-10-30 at 10 34 44 am](https://cloud.githubusercontent.com/assets/4286063/10837970/93cb83ba-7ef2-11e5-98cd-6401577058b9.png)

By the way, what's the user group with highest permission? is it group_admin or senior_admin?
Cause, i couldn't see the option "Import Domain via AXFR"

Thanks again and you're doing a great work! :)

**Comment by shupp** [comment]
This was just a template issue, I've pushed a fix for that.  Please test again.

Thanks!

Bill

**Comment by blackyzero** [comment]
That's great! i got it works.
Thanks a lot :+1:

**Comment by shupp** [comment]
Thanks for confirming.  I've released these changes in 0.13.2.
