### ISSUE TITLE
Thanks so much!

### ISSUE THREAD

**Issue by rjsocha** [shupp/VegaDNS#28]
I would like to thank you for your VegaDNS system. We are moving from  this version:

* 0.9.10 9/5/2006
    - Bill Shupp (hostmaster@shupp.org)
        - Update CREDITS
        - Fix php notice in records.php
        - Fix default soa records problems
        - Update Copyrights for 2006 in vegadns-stable

to other solution.

Your software worked for us for longer than a decade !  (in the manner if it's works = don't touch! :)

I wish to thank you for that!

(this was internal system, security was no concern)
I even implemetend SRV support long, long time ago:

```

    } else if($row['type'] == 'V') {
        $name=$row['host'];
        $pri=$row['distance'];
        $weight=$row['weight'];
        $port=$row['port'];
        $target=rtrim($row['val'],".");
        $ttl=$row['ttl'];
        $o=":$name:33:";
        $o .= sprintf("\%03o\%03o",(($pri&0xff00)>>8),$pri&0xff);
        $o .= sprintf("\%03o\%03o",(($weight&0xff00)>>8),$weight&0xff);
        $o .= sprintf("\%03o\%03o",(($port&0xff00)>>8),$port&0xff);
        foreach(preg_split("/[.]/",$target) as $c) {
                $c=substr($c,0,63);
                $o .= sprintf("\%03o%s",strlen($c)&0xff,$c);
        }
        $o .= "\\000:$ttl";
        $s ="$o\n";


```

tinydns rulez! 

Cheers :)

**Comment by shupp** [comment]
@rjsocha you're quite welcome, I'm glad you found it useful.  Thanks for the note!
