### ISSUE TITLE
feature request: logout redirect url (small code chage)

### ISSUE THREAD

**Issue by ytjohn** [shupp/VegaDNS#9]
Add a logout_redirect_url to src/config.php and index.php.  The purpose is to redirect users to a different page after they log out.

add some lines to src/config.php:
<pre>
// redirect users to a specific page upon logout, default is VegaDNS's index.php login page
// $logout_redirect_url = "http://www.example.com/";
</pre>

Then in index.php:
<pre>
121     // End session
122     $q = "delete from active_sessions where sid='".session_id()."'";
123     mysql_query($q) or die(mysql_error());
124     session_unset();
125     session_destroy();
126     // add redirect url to change to after logging out
127     if (!$logout_redirect_url) { $logout_redirect_url = "index.php"; } 
128     header("Location: ". $logout_redirect_url);
129     exit;
</pre>

**Comment by shupp** [comment]
Sorry for not responding to this, but I don't think this is needed in the main distribution.  It's an easy enough patch to maintain if you need it, though.
